package driver_micaz_osgi;
/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'BSMsg'
 * message type.
 */

public class BSMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 6;

    /** Create a new BSMsg of size 4. */
    public BSMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new BSMsg of the given data_length. */
    public BSMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BSMsg with the given data_length
     * and base offset.
     */
    public BSMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BSMsg using the given byte array
     * as backing store.
     */
    public BSMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BSMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public BSMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BSMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public BSMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BSMsg embedded in the given message
     * at the given base offset.
     */
    public BSMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BSMsg embedded in the given message
     * at the given base offset and length.
     */
    public BSMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <BSMsg> \n";
      try {
        s += "  [NodeID=0x"+Long.toHexString(get_NodeID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [RSSI_RAW=0x"+Long.toHexString(get_RSSI_RAW())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: NodeID
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'NodeID' is signed (false).
     */
    public static boolean isSigned_NodeID() {
        return false;
    }

    /**
     * Return whether the field 'NodeID' is an array (false).
     */
    public static boolean isArray_NodeID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'NodeID'
     */
    public static int offset_NodeID() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'NodeID'
     */
    public static int offsetBits_NodeID() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'NodeID'
     */
    public int get_NodeID() {
        return (int)getUIntBEElement(offsetBits_NodeID(), 16);
    }

    /**
     * Set the value of the field 'NodeID'
     */
    public void set_NodeID(int value) {
        setUIntBEElement(offsetBits_NodeID(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'NodeID'
     */
    public static int size_NodeID() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'NodeID'
     */
    public static int sizeBits_NodeID() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: RSSI_RAW
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'RSSI_RAW' is signed (false).
     */
    public static boolean isSigned_RSSI_RAW() {
        return false;
    }

    /**
     * Return whether the field 'RSSI_RAW' is an array (false).
     */
    public static boolean isArray_RSSI_RAW() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'RSSI_RAW'
     */
    public static int offset_RSSI_RAW() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'RSSI_RAW'
     */
    public static int offsetBits_RSSI_RAW() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'RSSI_RAW'
     */
    public int get_RSSI_RAW() {
        return (int)getUIntBEElement(offsetBits_RSSI_RAW(), 16);
    }

    /**
     * Set the value of the field 'RSSI_RAW'
     */
    public void set_RSSI_RAW(int value) {
        setUIntBEElement(offsetBits_RSSI_RAW(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'RSSI_RAW'
     */
    public static int size_RSSI_RAW() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'RSSI_RAW'
     */
    public static int sizeBits_RSSI_RAW() {
        return 16;
    }

}
