/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'MatMsg'
 * message type.
 */
package driver_micaz_osgi;

public class MatMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 12;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 3;

    /** Create a new MatMsg of size 12. */
    public MatMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new MatMsg of the given data_length. */
    public MatMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MatMsg with the given data_length
     * and base offset.
     */
    public MatMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MatMsg using the given byte array
     * as backing store.
     */
    public MatMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MatMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public MatMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MatMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public MatMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MatMsg embedded in the given message
     * at the given base offset.
     */
    public MatMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MatMsg embedded in the given message
     * at the given base offset and length.
     */
    public MatMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <MatMsg> \n";
      try {
        s += "  [node_rx=0x"+Long.toHexString(get_node_rx())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [node_tx=0x"+Long.toHexString(get_node_tx())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [event=0x"+Long.toHexString(get_event())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [seqNo=0x"+Long.toHexString(get_seqNo())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [battery=0x"+Long.toHexString(get_battery())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [timestamp=0x"+Long.toHexString(get_timestamp())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: node_rx
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'node_rx' is signed (false).
     */
    public static boolean isSigned_node_rx() {
        return false;
    }

    /**
     * Return whether the field 'node_rx' is an array (false).
     */
    public static boolean isArray_node_rx() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'node_rx'
     */
    public static int offset_node_rx() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'node_rx'
     */
    public static int offsetBits_node_rx() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'node_rx'
     */
    public int get_node_rx() {
        return (int)getUIntBEElement(offsetBits_node_rx(), 16);
    }

    /**
     * Set the value of the field 'node_rx'
     */
    public void set_node_rx(int value) {
        setUIntBEElement(offsetBits_node_rx(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'node_rx'
     */
    public static int size_node_rx() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'node_rx'
     */
    public static int sizeBits_node_rx() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: node_tx
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'node_tx' is signed (false).
     */
    public static boolean isSigned_node_tx() {
        return false;
    }

    /**
     * Return whether the field 'node_tx' is an array (false).
     */
    public static boolean isArray_node_tx() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'node_tx'
     */
    public static int offset_node_tx() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'node_tx'
     */
    public static int offsetBits_node_tx() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'node_tx'
     */
    public int get_node_tx() {
        return (int)getUIntBEElement(offsetBits_node_tx(), 16);
    }

    /**
     * Set the value of the field 'node_tx'
     */
    public void set_node_tx(int value) {
        setUIntBEElement(offsetBits_node_tx(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'node_tx'
     */
    public static int size_node_tx() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'node_tx'
     */
    public static int sizeBits_node_tx() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: event
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'event' is signed (false).
     */
    public static boolean isSigned_event() {
        return false;
    }

    /**
     * Return whether the field 'event' is an array (false).
     */
    public static boolean isArray_event() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'event'
     */
    public static int offset_event() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'event'
     */
    public static int offsetBits_event() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'event'
     */
    public int get_event() {
        return (int)getUIntBEElement(offsetBits_event(), 16);
    }

    /**
     * Set the value of the field 'event'
     */
    public void set_event(int value) {
        setUIntBEElement(offsetBits_event(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'event'
     */
    public static int size_event() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'event'
     */
    public static int sizeBits_event() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: seqNo
    //   Field type: int, unsigned
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'seqNo' is signed (false).
     */
    public static boolean isSigned_seqNo() {
        return false;
    }

    /**
     * Return whether the field 'seqNo' is an array (false).
     */
    public static boolean isArray_seqNo() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'seqNo'
     */
    public static int offset_seqNo() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'seqNo'
     */
    public static int offsetBits_seqNo() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'seqNo'
     */
    public int get_seqNo() {
        return (int)getUIntBEElement(offsetBits_seqNo(), 16);
    }

    /**
     * Set the value of the field 'seqNo'
     */
    public void set_seqNo(int value) {
        setUIntBEElement(offsetBits_seqNo(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'seqNo'
     */
    public static int size_seqNo() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'seqNo'
     */
    public static int sizeBits_seqNo() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: battery
    //   Field type: int, unsigned
    //   Offset (bits): 64
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'battery' is signed (false).
     */
    public static boolean isSigned_battery() {
        return false;
    }

    /**
     * Return whether the field 'battery' is an array (false).
     */
    public static boolean isArray_battery() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'battery'
     */
    public static int offset_battery() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'battery'
     */
    public static int offsetBits_battery() {
        return 64;
    }

    /**
     * Return the value (as a int) of the field 'battery'
     */
    public int get_battery() {
        return (int)getUIntBEElement(offsetBits_battery(), 16);
    }

    /**
     * Set the value of the field 'battery'
     */
    public void set_battery(int value) {
        setUIntBEElement(offsetBits_battery(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'battery'
     */
    public static int size_battery() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'battery'
     */
    public static int sizeBits_battery() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: timestamp
    //   Field type: int, unsigned
    //   Offset (bits): 80
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'timestamp' is signed (false).
     */
    public static boolean isSigned_timestamp() {
        return false;
    }

    /**
     * Return whether the field 'timestamp' is an array (false).
     */
    public static boolean isArray_timestamp() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'timestamp'
     */
    public static int offset_timestamp() {
        return (80 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'timestamp'
     */
    public static int offsetBits_timestamp() {
        return 80;
    }

    /**
     * Return the value (as a int) of the field 'timestamp'
     */
    public int get_timestamp() {
        return (int)getUIntBEElement(offsetBits_timestamp(), 16);
    }

    /**
     * Set the value of the field 'timestamp'
     */
    public void set_timestamp(int value) {
        setUIntBEElement(offsetBits_timestamp(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'timestamp'
     */
    public static int size_timestamp() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'timestamp'
     */
    public static int sizeBits_timestamp() {
        return 16;
    }

}